[package]
name = "mcsm-zip"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
structopt = "0.3.26"
zip = {version =  "2.2.2", default-features = false, features = ["time", "deflate"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"